import os
import subprocess
import shutil
from pathlib import Path
from src.config import Config

class PDFCompiler:
    def __init__(self):
        self.config = Config.get_instance()

    def compile_tex(self, tex_file_path: Path) -> Path:
        """
        Compiles a .tex file to PDF using pdflatex.
        Returns the path to the generated PDF.
        """
        if not tex_file_path.exists():
            raise FileNotFoundError(f"LaTeX file not found: {tex_file_path}")

        # Ensure output directory exists
        output_dir = self.config.OUTPUT_DIR
        
        # We need to run pdflatex from the directory where the .tex file is
        # or specify -output-directory. We'll use the latter.
        
        # Command to run pdflatex
        # We run it twice to resolve references/page numbers/labels
        cmd = [
            'pdflatex',
            '-interaction=nonstopmode',
            '-output-directory', str(output_dir),
            str(tex_file_path)
        ]

        print(f"Compiling {tex_file_path.name}...")
        
        try:
            # 1st Pass
            result = subprocess.run(cmd, capture_output=True, text=True, check=True)
            # 2nd Pass (often needed for layout/refs)
            result = subprocess.run(cmd, capture_output=True, text=True, check=True)
            
            pdf_filename = tex_file_path.with_suffix('.pdf').name
            pdf_path = output_dir / pdf_filename

            print(f"Compilation successful: {pdf_path}")
            self._cleanup(tex_file_path.stem)
            
            return pdf_path

        except subprocess.CalledProcessError as e:
            # If compilation fails, print stdout/stderr for debugging
            print("PDF Compilation Failed!")
            print("STDOUT:", e.stdout)
            print("STDERR:", e.stderr)
            raise e

    def _cleanup(self, file_stem: str):
        """
        Removes auxiliary files (.aux, .log, .out) generated by pdflatex.
        """
        exts = ['.aux', '.log', '.out']
        for ext in exts:
            file_to_remove = self.config.OUTPUT_DIR / (file_stem + ext)
            if file_to_remove.exists():
                file_to_remove.unlink()
